let data = [
  {
    _id: 1,
    name: "Almond",
    img: "/images/food/almond.jpg",
    price: 10,
    totalrating: 15,
    description:
      "The almond is the edible kernel of the fruit of the sweet almond tree. It is a bright white fruti and wrapped in a reddish brown cover. It is consumed as dry fruit, fried and/or salted. Some well-known products, such as nougat and marzipan, are made of almonds. ... It is consumed as dry fruit, fried and/or salted",
    rating: 4.5,
    slug: 1,
    stock: 304,
    category:'crops',
    coupon:'ten',
    discount:10
  },
  {
    _id: 2,
    name: "Bracoli",
    img: "/images/food/brokly.jpg",
    price: 20,
    totalrating: 125,
    description:
      "Broccoli has large flower heads, usually dark green, arranged in a tree-like structure branching out from a thick stalk which is usually light green. The mass of flower heads is surrounded by leaves. Broccoli resembles cauliflower, which is a different but closely related cultivar group of the same Brassica species.",
    rating: 5,
    slug: 2,
    stock: 134,
    category:'vegetable',
    coupon:'twenty',
    discount:20,
  },
  {
    _id: 3,
    name: "Chips",
    img: "/images/food/chips.jpg",
    price: 30,
    totalrating: 21,
    description:
      "a small usually thin and flat piece (as of wood or stone) cut, struck, or flaked off. b : a small piece of food: such as. (1) : a small, thin, crisp, usually salty piece of food typically prepared by frying, baking, or drying banana chips especially : potato chip — see also corn chip.",
    rating: 4,
    slug: 3,
    stock: 534,
    category:'snacks',
    coupon:'thirty',
    discount:30,
  },
  {
    _id: 4,
    name: "Franz Fri",
    img: "/images/food/fri.jpg",
    price: 40,
    totalrating: 22,
    description:
      "Fried potatoes are pieces of potato cooked in oil or fat. Main meals come with your choice of boiled or fried potatoes. Fried potatoes are better when the potatoes are cooked in duck fat. For fried potatoes, slice potatoes thinly and put them in a pan.",
    rating: 5,
    slug: 4,
    stock: 434,
    category:'snacks',
    coupon:'fourty',
    discount:40,
  },
  {
    _id: 5,
    name: "Family Pack",
    img: "/images/food/familypack.jpg",
    price: 150,
    totalrating: 55,
    description:
      "This 12-ct family pack of Snack Pack chocolate pudding cups has all the rich and ... See ingredients, nutrition, and other product information here.",
    rating: 4.5,
    slug: 5,
    stock: 0,
    category:'fruits',
    coupon:'fifty',
    discount:50,
  },
  {
    _id: 6,
    name: "Fruits",
    img: "/images/food/fruits.jpg",
    price: 120,
    totalrating: 25,
    description:
      "A fruit is a mature, ripened ovary, along with the contents of the ovary. The ovary is the ovule-bearing reproductive structure in the plant flower. ... Under the botanical definition of fruit, many things that are commonly called vegetables are in fact fruits (for example, eggplant, green beans, okra, and, yes, tomatoes).",
    rating: 15,
    slug: 6,
    stock: 10,
    category:'vegetables',
    coupon:'twenty',
    discount:20,
  },
  {
    _id: 7,
    name: "Masterd Oil",
    img: "/images/food/masterdoil.jpg",
    price: 150,
    totalrating: 145,
    description:
      "Mustard oil, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 3,
    slug: 7,
    stock: 454,
    category:'oils',
    coupon:'thirty',
    discount:30,
  },
  {
    _id: 8,
    name: "Milk",
    img: "/images/food/milk.png",
    price: 85,
    totalrating: 45,
    description:
      "Milk, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 8,
    stock: 54,
    category:'drinks',
    coupon:'fourty',
    discount:40,
  },
  {
    _id: 9,
    name: "Berger",
    img: "/images/food/berger.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Berger, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 9,
    stock: 54,
    category:'snacks',
    coupon:'fifty',
    discount:50,
  },
  {
    _id: 10,
    name: "Blackgrap",
    img: "/images/food/blackgrap.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Black Graps, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 10,
    stock: 54,
    category:'fruits',
    coupon:'sixty',
    discount:60,
  },
  {
    _id: 11,
    name: "chiken",
    img: "/images/food/chiken.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Chiken, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 11,
    stock: 54,
    category:'snacks',
    coupon:'seventy',
    discount:70,
  },
  {
    _id: 12,
    name: "carrot",
    img: "/images/food/carrot.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Carrot, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 12,
    stock: 54,
    category:'vegetables',
    coupon:'eighty',
    discount:80,
  },
  {
    _id: 13,
    name: "Doubleberger",
    img: "/images/food/doubleberger.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Double berger, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 13,
    stock: 54,
    category:'snacks',
  },
  {
    _id: 14,
    name: "Nigella",
    img: "/images/food/Nigella.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Nigella, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 14,
    stock: 54,
    category:'oils',
  },
  {
    _id: 15,
    name: "Senduce",
    img: "/images/food/senduce.jpg",
    price: 85,
    totalrating: 45,
    description:
      "Senduce, which is produced from the seeds of the mustard plant, is a common ingredient in Indian cuisine. Known for its strong flavor, pungent aroma, and high smoke point, it's often used for sautéing and stir-frying vegetables in many parts of the world, including India, Bangladesh, and Pakistan",
    rating: 4,
    slug: 15,
    stock: 54,
    category:'snacks',
  },
];

export default data;
